# Site settings
title: "Emanuel G. Andrade"
email: emanuelgandrade@gmail.com
description: "Blog pessoal"
baseurl: ""
url: "http://emanuelgandrade.com/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://s.gravatar.com/avatar/2af25bd2a15069633fb59293e872aadf?s=80"
google_analytics: "UA-86468321-1"
disqus_account: emanuelgandrade 
github_repository: https://github.com/emanuelgandrade
addthis_id: #ra-5812e6a115a44c35
post_limit: 5

# Social usernames/URLs
twitter_username: emanuelgandrade
github_username: emanuelgandrade
linkedin_link: https://br.linkedin.com/in/emanuelgandrade
google_plus_link: https://plus.google.com/+EmanuelAndradeg
stackoverflow_link: http://emanuelgandrade.com/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"mailto:emanuelgandrade@gmail.com?Subject=Hello%20again\">Emanuel G. Andrade</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]